#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.11
# from Racc grammer file "".
#

require 'racc/parser.rb'

require File.dirname(__FILE__) + '/parser.rex.rb'

module SQLParser
  class Parser < Racc::Parser

module_eval(<<'...end parser.racc/module_eval...', 'parser.racc', 321)

def self.parse(sql)
  new.scan_str(sql)
end
...end parser.racc/module_eval...
##### State transition tables begin ###

racc_action_table = [
    44,    70,   207,   212,    65,    91,    91,   101,     7,    94,
   218,     8,     7,   178,   124,     8,   219,   209,    44,   210,
   211,   212,    95,   134,    97,    98,    67,    99,   100,    67,
   135,   178,    18,   136,    71,    67,    44,    67,    67,   212,
    47,    48,   139,    32,    45,    36,    38,    39,    40,    41,
    18,    49,   120,    52,    47,    48,    68,    69,    47,    48,
    67,    32,    45,    36,    38,    39,    40,    41,    18,    49,
    44,    52,  -119,    28,   160,     7,    47,    48,     8,    32,
    45,    36,    38,    39,    40,    41,   161,    49,    44,    52,
   162,    28,   128,   129,    85,    84,   163,    14,   164,   165,
   166,   112,    18,  -119,  -119,  -119,    67,    60,    60,   173,
    47,    48,   174,    32,    45,    36,    38,    39,    40,    41,
    18,    49,    44,    52,    60,    28,   178,     7,    47,    48,
     8,    32,    45,    36,    38,    39,    40,    41,   104,    49,
    44,    52,   190,   212,   193,   125,   195,   196,    86,   132,
    18,   206,    83,   112,    18,    82,    60,    81,    44,   214,
  -138,   212,    47,    48,    80,    32,    45,    36,    38,    39,
    40,    41,    18,    49,    79,    52,    78,    77,    76,    75,
    47,    48,   130,    32,    45,    36,    38,    39,    40,    41,
    18,    49,    44,    52,   126,   140,   -75,    64,    47,    48,
    63,    32,    45,    36,    38,    39,    40,    41,   229,    49,
    44,    52,    94,    28,   133,   230,   147,   193,    60,   214,
    93,    54,    53,   144,    18,    95,   234,    97,    98,    12,
    99,   100,    47,    48,   236,    32,    45,    36,    38,    39,
    40,    41,    18,    49,    44,    52,   178,   140,    67,    18,
    47,    48,   241,    32,    45,    36,    38,    39,    40,    41,
    11,    49,   243,    52,   244,   245,     9,    67,   147,   nil,
    44,   nil,   nil,   140,   nil,   144,    18,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    47,    48,   nil,    32,    45,    36,
    38,    39,    40,    41,   147,    49,    44,    52,   nil,    28,
   nil,   144,    18,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    47,    48,   nil,    32,    45,    36,    38,    39,    40,    41,
   nil,    49,    44,    52,   nil,   212,   nil,   nil,    18,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    47,    48,   nil,    32,
    45,    36,    38,    39,    40,    41,   nil,    49,    44,    52,
   nil,    28,   nil,   nil,    18,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    47,    48,   nil,    32,    45,    36,    38,    39,
    40,    41,   nil,    49,    44,    52,   nil,    28,   nil,   nil,
    18,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    47,    48,
   nil,    32,    45,    36,    38,    39,    40,    41,   nil,    49,
    44,    52,   nil,    28,   nil,   nil,    18,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    94,   nil,    32,    45,    36,
    38,    39,    40,    41,   nil,    49,    44,    52,    95,   212,
    97,    98,    18,    99,   100,   200,   201,   nil,   nil,   nil,
    47,    48,   nil,    32,    45,    36,    38,    39,    40,    41,
   nil,    49,    44,    52,   nil,   212,   nil,   nil,    18,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    47,    48,   nil,    32,
    45,    36,    38,    39,    40,    41,   nil,    49,    44,    52,
   nil,   212,   nil,   nil,    18,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    47,    48,   nil,    32,    45,    36,    38,    39,
    40,    41,   nil,    49,    44,    52,   nil,   212,   nil,   nil,
    18,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    47,    48,
   nil,    32,    45,    36,    38,    39,    40,    41,   nil,    49,
    44,    52,   nil,   212,   nil,   nil,    18,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    47,    48,   nil,    32,    45,    36,
    38,    39,    40,    41,   nil,    49,    44,    52,   nil,    28,
   nil,   nil,    18,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    47,    48,   nil,    32,    45,    36,    38,    39,    40,    41,
   nil,    49,    44,    52,   nil,   212,   nil,   nil,    18,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    47,    48,   nil,    32,
    45,    36,    38,    39,    40,    41,   nil,    49,    44,    52,
   nil,    28,   nil,   nil,    18,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    47,    48,   nil,    32,    45,    36,    38,    39,
    40,    41,   nil,    49,    44,    52,   nil,   140,   nil,   nil,
    18,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    47,    48,
   nil,    32,    45,    36,    38,    39,    40,    41,   147,    49,
    44,    52,   nil,    28,   nil,   144,    18,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    47,    48,   nil,    32,    45,    36,
    38,    39,    40,    41,   nil,    49,    44,    52,   nil,   140,
   nil,   nil,    18,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    47,    48,   nil,    32,    45,    36,    38,    39,    40,    41,
   147,    49,    44,    52,   nil,    28,   nil,   144,    18,   nil,
   nil,   114,   nil,   nil,   nil,   nil,    47,    48,   nil,    32,
    45,    36,    38,    39,    40,    41,   nil,    49,    44,    52,
   nil,    28,   nil,   nil,    18,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    47,    48,   nil,    32,    45,    36,    38,    39,
    40,    41,   nil,    49,    44,    52,   nil,    28,   nil,   nil,
    18,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    47,    48,
   nil,    32,    45,    36,    38,    39,    40,    41,   nil,    49,
    44,    52,   nil,   140,   nil,   nil,    18,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    47,    48,   nil,    32,    45,    36,
    38,    39,    40,    41,   nil,    49,    44,    52,   nil,    28,
   nil,   144,    18,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    47,    48,   nil,    32,    45,    36,    38,    39,    40,    41,
   nil,    49,    44,    52,   nil,   140,   nil,     7,    18,   nil,
     8,   nil,   nil,   nil,   nil,   nil,    47,    48,   nil,    32,
    45,    36,    38,    39,    40,    41,   147,    49,    44,    52,
   nil,    28,   nil,   144,    18,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    47,    48,   nil,    32,    45,    36,    38,    39,
    40,    41,   nil,    49,    44,    52,   nil,    28,   nil,   nil,
    18,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    47,    48,
   nil,    32,    45,    36,    38,    39,    40,    41,   nil,    49,
   nil,    52,   nil,   nil,   nil,   nil,    18,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    47,    48,   nil,    32,    45,    36,
    38,    39,    40,    41,   nil,    49,   nil,    52,   179,   180,
   nil,   181,   182,   183,   nil,   nil,   nil,   nil,   184,   185,
   186,   187,   188,   189 ]

racc_action_check = [
   180,    22,   176,   180,    17,    54,   126,    56,     0,   105,
   183,     0,   190,   202,    83,   190,   183,   179,   241,   179,
   179,   241,   105,    98,   105,   105,    17,   105,   105,    56,
    99,   176,   180,   100,    22,   101,   234,    54,   126,   234,
   180,   180,   103,   180,   180,   180,   180,   180,   180,   180,
   241,   180,    81,   180,    83,    83,    21,    21,   241,   241,
    75,   241,   241,   241,   241,   241,   241,   241,   234,   241,
   214,   241,    20,   214,   114,   214,   234,   234,   214,   234,
   234,   234,   234,   234,   234,   234,   115,   234,     8,   234,
   116,     8,    89,    89,    49,    49,   117,     8,   118,   119,
   123,    74,   214,    20,    20,    20,    65,   132,   133,   138,
   214,   214,   139,   214,   214,   214,   214,   214,   214,   214,
     8,   214,   212,   214,    63,   212,   141,   212,     8,     8,
   212,     8,     8,     8,     8,     8,     8,     8,    62,     8,
   211,     8,   144,   211,   145,    84,   168,   169,    52,    95,
   174,   175,    46,   177,   212,    45,    94,    44,   209,   181,
    42,   209,   212,   212,    41,   212,   212,   212,   212,   212,
   212,   212,   211,   212,    40,   212,    39,    38,    36,    33,
   211,   211,    93,   211,   211,   211,   211,   211,   211,   211,
   209,   211,   200,   211,    87,   200,    18,    16,   209,   209,
    13,   209,   209,   209,   209,   209,   209,   209,   201,   209,
   196,   209,    55,   196,    96,   203,   200,   208,    12,   210,
    55,    11,     9,   200,   200,    55,   213,    55,    55,     7,
    55,    55,   200,   200,   218,   200,   200,   200,   200,   200,
   200,   200,   196,   200,   104,   200,   228,   104,   229,   230,
   196,   196,   231,   196,   196,   196,   196,   196,   196,   196,
     4,   196,   235,   196,   237,   238,     1,   245,   104,   nil,
   193,   nil,   nil,   193,   nil,   104,   104,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   104,   104,   nil,   104,   104,   104,
   104,   104,   104,   104,   193,   104,    80,   104,   nil,    80,
   nil,   193,   193,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   193,   193,   nil,   193,   193,   193,   193,   193,   193,   193,
   nil,   193,   189,   193,   nil,   189,   nil,   nil,    80,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    80,    80,   nil,    80,
    80,    80,    80,    80,    80,    80,   nil,    80,    79,    80,
   nil,    79,   nil,   nil,   189,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   189,   189,   nil,   189,   189,   189,   189,   189,
   189,   189,   nil,   189,    23,   189,   nil,    23,   nil,   nil,
    79,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    79,    79,
   nil,    79,    79,    79,    79,    79,    79,    79,   nil,    79,
    28,    79,   nil,    28,   nil,   nil,    23,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   171,   nil,    23,    23,    23,
    23,    23,    23,    23,   nil,    23,   188,    23,   171,   188,
   171,   171,    28,   171,   171,   171,   171,   nil,   nil,   nil,
    28,    28,   nil,    28,    28,    28,    28,    28,    28,    28,
   nil,    28,   187,    28,   nil,   187,   nil,   nil,   188,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   188,   188,   nil,   188,
   188,   188,   188,   188,   188,   188,   nil,   188,   186,   188,
   nil,   186,   nil,   nil,   187,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   187,   187,   nil,   187,   187,   187,   187,   187,
   187,   187,   nil,   187,   185,   187,   nil,   185,   nil,   nil,
   186,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   186,   186,
   nil,   186,   186,   186,   186,   186,   186,   186,   nil,   186,
   184,   186,   nil,   184,   nil,   nil,   185,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   185,   185,   nil,   185,   185,   185,
   185,   185,   185,   185,   nil,   185,    78,   185,   nil,    78,
   nil,   nil,   184,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   184,   184,   nil,   184,   184,   184,   184,   184,   184,   184,
   nil,   184,   182,   184,   nil,   182,   nil,   nil,    78,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    78,    78,   nil,    78,
    78,    78,    78,    78,    78,    78,   nil,    78,    68,    78,
   nil,    68,   nil,   nil,   182,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   182,   182,   nil,   182,   182,   182,   182,   182,
   182,   182,   nil,   182,   178,   182,   nil,   178,   nil,   nil,
    68,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    68,    68,
   nil,    68,    68,    68,    68,    68,    68,    68,   178,    68,
    77,    68,   nil,    77,   nil,   178,   178,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   178,   178,   nil,   178,   178,   178,
   178,   178,   178,   178,   nil,   178,   173,   178,   nil,   173,
   nil,   nil,    77,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    77,    77,   nil,    77,    77,    77,    77,    77,    77,    77,
   173,    77,    76,    77,   nil,    76,   nil,   173,   173,   nil,
   nil,    76,   nil,   nil,   nil,   nil,   173,   173,   nil,   173,
   173,   173,   173,   173,   173,   173,   nil,   173,    71,   173,
   nil,    71,   nil,   nil,    76,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    76,    76,   nil,    76,    76,    76,    76,    76,
    76,    76,   nil,    76,    70,    76,   nil,    70,   nil,   nil,
    71,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    71,    71,
   nil,    71,    71,    71,    71,    71,    71,    71,   nil,    71,
   147,    71,   nil,   147,   nil,   nil,    70,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    70,    70,   nil,    70,    70,    70,
    70,    70,    70,    70,   nil,    70,    69,    70,   nil,    69,
   nil,   147,   147,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   147,   147,   nil,   147,   147,   147,   147,   147,   147,   147,
   nil,   147,   140,   147,   nil,   140,   nil,   140,    69,   nil,
   140,   nil,   nil,   nil,   nil,   nil,    69,    69,   nil,    69,
    69,    69,    69,    69,    69,    69,   140,    69,    64,    69,
   nil,    64,   nil,   140,   140,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   140,   140,   nil,   140,   140,   140,   140,   140,
   140,   140,   nil,   140,   130,   140,   nil,   130,   nil,   nil,
    64,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    64,    64,
   nil,    64,    64,    64,    64,    64,    64,    64,   nil,    64,
   nil,    64,   nil,   nil,   nil,   nil,   130,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   130,   130,   nil,   130,   130,   130,
   130,   130,   130,   130,   nil,   130,   nil,   130,   143,   143,
   nil,   143,   143,   143,   nil,   nil,   nil,   nil,   143,   143,
   143,   143,   143,   143 ]

racc_action_pointer = [
    -2,   266,   nil,   nil,   258,   nil,   nil,   218,    83,   222,
   nil,   218,   181,   184,   nil,   nil,   193,   -11,   147,   nil,
    58,    11,   -13,   369,   nil,   nil,   nil,   nil,   395,   nil,
   nil,   nil,   nil,   130,   nil,   nil,   170,   nil,   169,   168,
   166,   156,   105,   nil,   108,   150,    97,   nil,   nil,    38,
   nil,   nil,    89,   nil,     0,   208,    -8,   nil,   nil,   nil,
   nil,   nil,   112,    87,   863,    69,   nil,   nil,   603,   811,
   759,   733,   nil,   nil,    92,    23,   707,   655,   551,   343,
   291,    47,   nil,     9,    89,   nil,   nil,   190,   nil,    86,
   nil,   nil,   nil,   174,   119,   131,   196,   nil,     2,     9,
    12,    -2,   nil,    15,   239,     5,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    65,    77,    81,    87,    89,    90,
   nil,   nil,   nil,    95,   nil,   nil,     1,   nil,   nil,   nil,
   889,   nil,    70,    71,   nil,   nil,   nil,   nil,    81,   109,
   837,    88,   nil,   919,   134,   113,   nil,   785,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   137,   143,
   nil,   411,   nil,   681,   113,   142,    -7,   144,   629,   -13,
    -5,   151,   577,   -19,   525,   499,   473,   447,   421,   317,
     2,   nil,   nil,   265,   nil,   nil,   205,   nil,   nil,   nil,
   187,   200,   -25,   211,   nil,   nil,   nil,   nil,   186,   153,
   211,   135,   117,   195,    65,   nil,   nil,   nil,   199,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   208,   211,
   212,   221,   nil,   nil,    31,   253,   nil,   255,   261,   nil,
   nil,    13,   nil,   nil,   nil,   230,   nil,   nil ]

racc_action_default = [
  -150,  -150,    -1,    -2,    -4,   -15,   -16,  -150,  -150,  -150,
    -3,  -150,  -150,   -20,   -21,   -22,   -24,   -27,  -144,  -102,
  -103,  -106,  -109,  -150,  -111,  -112,  -113,  -114,  -150,  -116,
  -117,  -118,  -120,  -150,  -122,  -123,  -150,  -125,  -150,  -150,
  -150,  -150,  -131,  -132,  -136,  -150,  -150,  -142,  -143,  -150,
  -147,  -148,  -150,   248,  -150,  -150,   -32,   -33,   -35,   -36,
   -75,   -19,   -52,  -150,  -150,  -150,   -26,  -144,  -150,  -150,
  -150,  -150,  -110,  -119,  -150,  -150,  -150,  -150,  -150,  -150,
  -150,  -134,  -135,  -150,  -150,  -146,  -149,    -5,    -7,   -11,
    -9,   -10,   -17,  -150,  -150,  -150,  -150,   -40,   -42,   -44,
   -45,  -150,   -31,   -54,  -150,   -29,   -23,   -25,  -104,  -105,
  -107,  -108,  -115,  -121,  -150,  -150,  -150,  -150,  -150,  -150,
  -133,  -137,  -139,  -150,  -141,  -145,  -150,    -8,   -12,   -13,
  -150,   -37,  -150,  -150,   -41,   -43,   -46,   -30,   -59,  -150,
  -150,   -53,   -61,  -150,  -150,   -78,   -80,  -150,   -83,   -84,
   -85,   -87,   -88,   -89,   -90,   -91,   -92,   -99,  -100,  -101,
  -124,  -126,  -127,  -128,  -129,  -130,  -140,    -6,  -150,   -69,
   -38,  -150,   -28,  -150,  -150,  -150,  -150,  -101,  -150,  -150,
  -150,  -150,  -150,  -150,  -150,  -150,  -150,  -150,  -150,  -150,
  -150,   -34,   -74,  -150,   -82,   -18,  -150,   -39,   -47,   -48,
  -150,  -150,   -60,   -55,   -57,   -58,   -14,   -86,   -79,  -150,
  -150,  -150,  -150,  -150,  -150,   -65,   -66,   -71,  -150,   -73,
   -93,   -94,   -95,   -96,   -97,   -98,   -81,   -68,   -49,  -150,
  -150,  -150,   -64,   -70,  -150,  -150,   -72,  -150,   -51,   -77,
   -56,  -150,   -63,   -67,   -50,  -150,   -62,   -76 ]

racc_goto_table = [
    66,    17,   215,   192,    56,    55,   141,    88,   168,    62,
   191,   110,   111,   108,   109,   103,   138,   172,    13,    61,
   197,    74,   205,   198,   204,    15,   199,    92,   237,   238,
   203,   232,   127,     1,    87,    10,   208,    90,   226,   102,
   194,     4,   176,     3,     2,   123,    72,   191,   107,    73,
   121,   122,   nil,   nil,   nil,    56,   105,    17,   113,   213,
   nil,   217,   nil,   220,   221,   222,   223,   224,   225,   115,
   116,   117,   118,   119,   227,   202,   191,   nil,   205,   167,
   240,   106,   nil,   nil,   137,   nil,   131,   nil,   231,   nil,
   233,   nil,   235,   nil,    73,    73,    73,    73,   nil,   nil,
   nil,   nil,   228,   nil,   nil,   nil,   nil,   nil,   nil,    90,
   nil,   nil,   nil,   242,   nil,   nil,   nil,   nil,   nil,   nil,
   246,   nil,   nil,   169,   170,    56,   171,   nil,   nil,   nil,
   nil,   nil,   nil,   177,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   169,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    74,   nil,   169,   nil,   nil,
   nil,   nil,   239,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   247 ]

racc_goto_check = [
    10,    21,    45,    28,    26,    14,    35,     7,    16,    22,
    11,    58,    58,    56,    56,    23,    24,    25,    17,    18,
    32,    21,    40,    33,    39,    19,    34,    15,    36,    37,
    38,    45,     9,     1,     6,     5,    49,    10,    50,    10,
    51,     4,    35,     3,     2,    60,    61,    11,    10,    57,
    72,    73,   nil,   nil,   nil,    26,    14,    21,    10,    43,
   nil,    43,   nil,    43,    43,    43,    43,    43,    43,    21,
    21,    21,    21,    21,    16,    35,    11,   nil,    40,     7,
    39,    19,   nil,   nil,    10,   nil,    26,   nil,    43,   nil,
    43,   nil,    16,   nil,    57,    57,    57,    57,   nil,   nil,
   nil,   nil,    35,   nil,   nil,   nil,   nil,   nil,   nil,    10,
   nil,   nil,   nil,    43,   nil,   nil,   nil,   nil,   nil,   nil,
    43,   nil,   nil,    21,    26,    26,    14,   nil,   nil,   nil,
   nil,   nil,   nil,    21,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    21,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    21,   nil,    21,   nil,   nil,
   nil,   nil,    10,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    10 ]

racc_goto_pointer = [
   nil,    33,    44,    43,    41,    31,   -20,   -47,   nil,   -57,
   -17,  -134,   nil,   nil,    -7,   -28,  -122,    10,     6,    17,
   nil,    -7,    -4,   -47,   -87,  -121,    -8,   nil,  -141,   nil,
   nil,   nil,  -151,  -148,  -145,   -98,  -201,  -200,  -144,  -150,
  -152,   nil,   nil,  -121,   nil,  -179,   nil,   nil,   nil,  -142,
  -155,  -107,   nil,   nil,   nil,   nil,   -55,    26,   -59,   nil,
   -38,    23,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   -33,   -32,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   175,   nil,   nil,   nil,    89,   nil,
    34,   142,     5,     6,   nil,   nil,   nil,   nil,   nil,   nil,
    16,   159,   nil,   nil,   nil,   nil,    35,    57,   216,    58,
    59,    96,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    26,   158,   152,   143,   153,   nil,   154,   155,   156,   145,
   146,   148,   149,   150,   151,   157,    19,    20,    21,    22,
    23,    24,    25,    27,    29,    30,    31,    33,    37,    42,
    43,    46,   nil,   nil,    50,    51 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 61, :_reduce_none,
  1, 62, :_reduce_none,
  2, 63, :_reduce_3,
  0, 65, :_reduce_none,
  3, 65, :_reduce_5,
  3, 66, :_reduce_6,
  1, 66, :_reduce_none,
  2, 67, :_reduce_8,
  1, 68, :_reduce_none,
  1, 68, :_reduce_10,
  0, 69, :_reduce_11,
  1, 69, :_reduce_12,
  1, 69, :_reduce_13,
  3, 71, :_reduce_14,
  1, 64, :_reduce_none,
  1, 64, :_reduce_none,
  4, 73, :_reduce_17,
  4, 75, :_reduce_18,
  3, 72, :_reduce_19,
  2, 72, :_reduce_20,
  1, 77, :_reduce_21,
  1, 77, :_reduce_22,
  3, 79, :_reduce_23,
  1, 79, :_reduce_none,
  3, 80, :_reduce_25,
  2, 80, :_reduce_26,
  1, 80, :_reduce_none,
  4, 78, :_reduce_28,
  2, 82, :_reduce_29,
  3, 74, :_reduce_30,
  2, 74, :_reduce_31,
  1, 74, :_reduce_none,
  1, 74, :_reduce_none,
  1, 88, :_reduce_none,
  1, 87, :_reduce_none,
  1, 87, :_reduce_none,
  3, 89, :_reduce_37,
  4, 89, :_reduce_38,
  5, 90, :_reduce_39,
  1, 91, :_reduce_40,
  2, 91, :_reduce_41,
  1, 91, :_reduce_42,
  2, 91, :_reduce_43,
  1, 91, :_reduce_44,
  1, 91, :_reduce_45,
  2, 91, :_reduce_46,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  2, 93, :_reduce_49,
  4, 94, :_reduce_50,
  1, 96, :_reduce_none,
  0, 83, :_reduce_none,
  2, 83, :_reduce_53,
  0, 84, :_reduce_none,
  3, 84, :_reduce_55,
  3, 98, :_reduce_56,
  1, 98, :_reduce_none,
  1, 99, :_reduce_none,
  0, 85, :_reduce_none,
  2, 85, :_reduce_60,
  1, 101, :_reduce_none,
  6, 102, :_reduce_62,
  5, 102, :_reduce_63,
  4, 104, :_reduce_64,
  3, 104, :_reduce_65,
  1, 105, :_reduce_none,
  3, 105, :_reduce_67,
  3, 76, :_reduce_68,
  1, 76, :_reduce_none,
  4, 106, :_reduce_70,
  3, 106, :_reduce_71,
  4, 107, :_reduce_72,
  3, 107, :_reduce_73,
  2, 108, :_reduce_74,
  1, 86, :_reduce_75,
  3, 97, :_reduce_76,
  1, 97, :_reduce_none,
  1, 95, :_reduce_none,
  3, 95, :_reduce_79,
  1, 109, :_reduce_none,
  3, 109, :_reduce_81,
  2, 110, :_reduce_82,
  1, 110, :_reduce_none,
  1, 111, :_reduce_none,
  1, 112, :_reduce_none,
  3, 112, :_reduce_86,
  1, 113, :_reduce_none,
  1, 113, :_reduce_none,
  1, 113, :_reduce_none,
  1, 113, :_reduce_none,
  1, 113, :_reduce_none,
  1, 113, :_reduce_none,
  3, 114, :_reduce_93,
  3, 114, :_reduce_94,
  3, 114, :_reduce_95,
  3, 114, :_reduce_96,
  3, 114, :_reduce_97,
  3, 114, :_reduce_98,
  1, 103, :_reduce_none,
  1, 103, :_reduce_none,
  1, 115, :_reduce_none,
  1, 81, :_reduce_none,
  1, 81, :_reduce_none,
  3, 116, :_reduce_104,
  3, 116, :_reduce_105,
  1, 116, :_reduce_none,
  3, 118, :_reduce_107,
  3, 118, :_reduce_108,
  1, 118, :_reduce_none,
  2, 119, :_reduce_110,
  1, 119, :_reduce_none,
  1, 121, :_reduce_none,
  1, 121, :_reduce_none,
  1, 121, :_reduce_none,
  3, 121, :_reduce_115,
  1, 122, :_reduce_none,
  1, 122, :_reduce_none,
  1, 124, :_reduce_none,
  1, 124, :_reduce_none,
  1, 125, :_reduce_120,
  3, 100, :_reduce_121,
  1, 100, :_reduce_none,
  1, 127, :_reduce_none,
  4, 123, :_reduce_124,
  1, 123, :_reduce_none,
  4, 128, :_reduce_126,
  4, 128, :_reduce_127,
  4, 128, :_reduce_128,
  4, 128, :_reduce_129,
  4, 128, :_reduce_130,
  1, 126, :_reduce_none,
  1, 126, :_reduce_none,
  3, 129, :_reduce_133,
  2, 129, :_reduce_134,
  2, 129, :_reduce_135,
  1, 129, :_reduce_136,
  3, 130, :_reduce_137,
  1, 131, :_reduce_none,
  1, 132, :_reduce_none,
  2, 133, :_reduce_140,
  1, 133, :_reduce_141,
  1, 120, :_reduce_142,
  1, 120, :_reduce_143,
  1, 70, :_reduce_144,
  3, 117, :_reduce_145,
  2, 117, :_reduce_146,
  1, 117, :_reduce_none,
  1, 134, :_reduce_none,
  2, 135, :_reduce_149 ]

racc_reduce_n = 150

racc_shift_n = 248

racc_token_table = {
  false => 0,
  :error => 1,
  :ORDER => 2,
  :BY => 3,
  :comma => 4,
  :unsigned_integer => 5,
  :ASC => 6,
  :DESC => 7,
  :left_paren => 8,
  :right_paren => 9,
  :INSERT => 10,
  :INTO => 11,
  :VALUES => 12,
  :SELECT => 13,
  :asterisk => 14,
  :AS => 15,
  :FROM => 16,
  :CROSS => 17,
  :JOIN => 18,
  :INNER => 19,
  :LEFT => 20,
  :OUTER => 21,
  :RIGHT => 22,
  :FULL => 23,
  :ON => 24,
  :USING => 25,
  :WHERE => 26,
  :GROUP => 27,
  :HAVING => 28,
  :NOT => 29,
  :BETWEEN => 30,
  :AND => 31,
  :IN => 32,
  :LIKE => 33,
  :IS => 34,
  :NULL => 35,
  :EXISTS => 36,
  :identifier => 37,
  :OR => 38,
  :equals_operator => 39,
  :not_equals_operator => 40,
  :less_than_operator => 41,
  :greater_than_operator => 42,
  :less_than_or_equals_operator => 43,
  :greater_than_or_equals_operator => 44,
  :plus_sign => 45,
  :minus_sign => 46,
  :solidus => 47,
  :CURRENT_USER => 48,
  :period => 49,
  :COUNT => 50,
  :AVG => 51,
  :MAX => 52,
  :MIN => 53,
  :SUM => 54,
  :E => 55,
  :quote => 56,
  :character_string_literal => 57,
  :DATE => 58,
  :date_string => 59 }

racc_nt_base = 60

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "ORDER",
  "BY",
  "comma",
  "unsigned_integer",
  "ASC",
  "DESC",
  "left_paren",
  "right_paren",
  "INSERT",
  "INTO",
  "VALUES",
  "SELECT",
  "asterisk",
  "AS",
  "FROM",
  "CROSS",
  "JOIN",
  "INNER",
  "LEFT",
  "OUTER",
  "RIGHT",
  "FULL",
  "ON",
  "USING",
  "WHERE",
  "GROUP",
  "HAVING",
  "NOT",
  "BETWEEN",
  "AND",
  "IN",
  "LIKE",
  "IS",
  "NULL",
  "EXISTS",
  "identifier",
  "OR",
  "equals_operator",
  "not_equals_operator",
  "less_than_operator",
  "greater_than_operator",
  "less_than_or_equals_operator",
  "greater_than_or_equals_operator",
  "plus_sign",
  "minus_sign",
  "solidus",
  "CURRENT_USER",
  "period",
  "COUNT",
  "AVG",
  "MAX",
  "MIN",
  "SUM",
  "E",
  "quote",
  "character_string_literal",
  "DATE",
  "date_string",
  "$start",
  "direct_sql_statement",
  "direct_sql_data_statement",
  "direct_select_statement_multiple_rows",
  "query_expression",
  "order_by_clause",
  "sort_specification_list",
  "sort_specification",
  "sort_key",
  "ordering_specification",
  "column_name",
  "subquery",
  "query_specification",
  "insert_specification",
  "table_reference",
  "value_list",
  "in_value_list",
  "select_list",
  "table_expression",
  "select_sublist",
  "derived_column",
  "value_expression",
  "from_clause",
  "where_clause",
  "group_by_clause",
  "having_clause",
  "table_name",
  "joined_table",
  "table_subquery",
  "cross_join",
  "qualified_join",
  "join_type",
  "join_specification",
  "join_condition",
  "named_columns_join",
  "search_condition",
  "join_column_list",
  "column_name_list",
  "grouping_column_reference_list",
  "grouping_column_reference",
  "column_reference",
  "row_subquery",
  "between_predicate",
  "row_value_constructor",
  "in_predicate",
  "in_predicate_value",
  "like_predicate",
  "null_predicate",
  "exists_predicate",
  "boolean_term",
  "boolean_factor",
  "boolean_test",
  "boolean_primary",
  "predicate",
  "comparison_predicate",
  "row_value_constructor_element",
  "numeric_value_expression",
  "general_literal",
  "term",
  "factor",
  "sign",
  "value_expression_primary",
  "unsigned_value_specification",
  "set_function_specification",
  "unsigned_literal",
  "general_value_specification",
  "unsigned_numeric_literal",
  "qualifier",
  "general_set_function",
  "exact_numeric_literal",
  "approximate_numeric_literal",
  "mantissa",
  "exponent",
  "signed_integer",
  "datetime_literal",
  "date_literal" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

module_eval(<<'.,.,', 'parser.racc', 11)
  def _reduce_3(val, _values, result)
     result = SQLParser::Statement::DirectSelect.new(val[0], val[1]) 
    result
  end
.,.,

# reduce 4 omitted

module_eval(<<'.,.,', 'parser.racc', 16)
  def _reduce_5(val, _values, result)
     result = SQLParser::Statement::OrderBy.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 19)
  def _reduce_6(val, _values, result)
     result = Array(val[0]) + Array(val[2]) 
    result
  end
.,.,

# reduce 7 omitted

module_eval(<<'.,.,', 'parser.racc', 23)
  def _reduce_8(val, _values, result)
     result = val[1].new(val[0]) 
    result
  end
.,.,

# reduce 9 omitted

module_eval(<<'.,.,', 'parser.racc', 27)
  def _reduce_10(val, _values, result)
     result = SQLParser::Statement::Integer.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 30)
  def _reduce_11(val, _values, result)
     result = SQLParser::Statement::Ascending 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 31)
  def _reduce_12(val, _values, result)
     result = SQLParser::Statement::Ascending 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 32)
  def _reduce_13(val, _values, result)
     result = SQLParser::Statement::Descending 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 37)
  def _reduce_14(val, _values, result)
     result = SQLParser::Statement::Subquery.new(val[1]) 
    result
  end
.,.,

# reduce 15 omitted

# reduce 16 omitted

module_eval(<<'.,.,', 'parser.racc', 44)
  def _reduce_17(val, _values, result)
     result = SQLParser::Statement::Insert.new(val[2], nil, val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 48)
  def _reduce_18(val, _values, result)
     result = SQLParser::Statement::InValueList.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 51)
  def _reduce_19(val, _values, result)
     result = SQLParser::Statement::Select.new(val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 52)
  def _reduce_20(val, _values, result)
     result = SQLParser::Statement::Select.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 55)
  def _reduce_21(val, _values, result)
     result = SQLParser::Statement::All.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 56)
  def _reduce_22(val, _values, result)
     result = SQLParser::Statement::SelectList.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 59)
  def _reduce_23(val, _values, result)
     result = Array(val[0]) + Array(val[2]) 
    result
  end
.,.,

# reduce 24 omitted

module_eval(<<'.,.,', 'parser.racc', 63)
  def _reduce_25(val, _values, result)
     result = SQLParser::Statement::As.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 64)
  def _reduce_26(val, _values, result)
     result = SQLParser::Statement::As.new(val[0], val[1]) 
    result
  end
.,.,

# reduce 27 omitted

module_eval(<<'.,.,', 'parser.racc', 68)
  def _reduce_28(val, _values, result)
     result = SQLParser::Statement::TableExpression.new(val[0], val[1], val[2], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 71)
  def _reduce_29(val, _values, result)
     result = SQLParser::Statement::FromClause.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 74)
  def _reduce_30(val, _values, result)
     result = SQLParser::Statement::As.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 75)
  def _reduce_31(val, _values, result)
     result = SQLParser::Statement::As.new(val[0], val[1]) 
    result
  end
.,.,

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

module_eval(<<'.,.,', 'parser.racc', 87)
  def _reduce_37(val, _values, result)
     result = SQLParser::Statement::CrossJoin.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 88)
  def _reduce_38(val, _values, result)
     result = SQLParser::Statement::CrossJoin.new(val[0], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 91)
  def _reduce_39(val, _values, result)
     result = val[1].new(val[0], val[3], val[4]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 94)
  def _reduce_40(val, _values, result)
     result = SQLParser::Statement::InnerJoin 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 95)
  def _reduce_41(val, _values, result)
     result = SQLParser::Statement::LeftOuterJoin 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 96)
  def _reduce_42(val, _values, result)
     result = SQLParser::Statement::LeftJoin 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 97)
  def _reduce_43(val, _values, result)
     result = SQLParser::Statement::RightOuterJoin 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 98)
  def _reduce_44(val, _values, result)
     result = SQLParser::Statement::RightJoin 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 99)
  def _reduce_45(val, _values, result)
     result = SQLParser::Statement::FullJoin 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 100)
  def _reduce_46(val, _values, result)
     result = SQLParser::Statement::FullOuterJoin 
    result
  end
.,.,

# reduce 47 omitted

# reduce 48 omitted

module_eval(<<'.,.,', 'parser.racc', 107)
  def _reduce_49(val, _values, result)
     result = SQLParser::Statement::On.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 110)
  def _reduce_50(val, _values, result)
     result = SQLParser::Statement::Using.new(val[2]) 
    result
  end
.,.,

# reduce 51 omitted

# reduce 52 omitted

module_eval(<<'.,.,', 'parser.racc', 117)
  def _reduce_53(val, _values, result)
     result = SQLParser::Statement::WhereClause.new(val[1]) 
    result
  end
.,.,

# reduce 54 omitted

module_eval(<<'.,.,', 'parser.racc', 121)
  def _reduce_55(val, _values, result)
     result = SQLParser::Statement::GroupByClause.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 124)
  def _reduce_56(val, _values, result)
     result = Array(val[0]) + Array(val[2]) 
    result
  end
.,.,

# reduce 57 omitted

# reduce 58 omitted

# reduce 59 omitted

module_eval(<<'.,.,', 'parser.racc', 132)
  def _reduce_60(val, _values, result)
     result = SQLParser::Statement::HavingClause.new(val[1]) 
    result
  end
.,.,

# reduce 61 omitted

module_eval(<<'.,.,', 'parser.racc', 139)
  def _reduce_62(val, _values, result)
     result = SQLParser::Statement::Not.new(SQLParser::Statement::Between.new(val[0], val[3], val[5])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 140)
  def _reduce_63(val, _values, result)
     result = SQLParser::Statement::Between.new(val[0], val[2], val[4]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 143)
  def _reduce_64(val, _values, result)
     result = SQLParser::Statement::Not.new(SQLParser::Statement::In.new(val[0], val[3])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 144)
  def _reduce_65(val, _values, result)
     result = SQLParser::Statement::In.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 66 omitted

module_eval(<<'.,.,', 'parser.racc', 148)
  def _reduce_67(val, _values, result)
     result = SQLParser::Statement::InValueList.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 151)
  def _reduce_68(val, _values, result)
     result = Array(val[0]) + Array(val[2]) 
    result
  end
.,.,

# reduce 69 omitted

module_eval(<<'.,.,', 'parser.racc', 158)
  def _reduce_70(val, _values, result)
     result = SQLParser::Statement::Not.new(SQLParser::Statement::Like.new(val[0], val[3])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 159)
  def _reduce_71(val, _values, result)
     result = SQLParser::Statement::Like.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 162)
  def _reduce_72(val, _values, result)
     result = SQLParser::Statement::Not.new(SQLParser::Statement::Is.new(val[0], SQLParser::Statement::Null.new)) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 163)
  def _reduce_73(val, _values, result)
     result = SQLParser::Statement::Is.new(val[0], SQLParser::Statement::Null.new) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 166)
  def _reduce_74(val, _values, result)
     result = SQLParser::Statement::Exists.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 170)
  def _reduce_75(val, _values, result)
     result = SQLParser::Statement::Table.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 173)
  def _reduce_76(val, _values, result)
     result = Array(val[0]) + Array(val[2]) 
    result
  end
.,.,

# reduce 77 omitted

# reduce 78 omitted

module_eval(<<'.,.,', 'parser.racc', 179)
  def _reduce_79(val, _values, result)
     result = SQLParser::Statement::Or.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 80 omitted

module_eval(<<'.,.,', 'parser.racc', 183)
  def _reduce_81(val, _values, result)
     result = SQLParser::Statement::And.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 186)
  def _reduce_82(val, _values, result)
     result = SQLParser::Statement::Not.new(val[1]) 
    result
  end
.,.,

# reduce 83 omitted

# reduce 84 omitted

# reduce 85 omitted

module_eval(<<'.,.,', 'parser.racc', 194)
  def _reduce_86(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 87 omitted

# reduce 88 omitted

# reduce 89 omitted

# reduce 90 omitted

# reduce 91 omitted

# reduce 92 omitted

module_eval(<<'.,.,', 'parser.racc', 205)
  def _reduce_93(val, _values, result)
     result = SQLParser::Statement::Equals.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 206)
  def _reduce_94(val, _values, result)
     result = SQLParser::Statement::Not.new(SQLParser::Statement::Equals.new(val[0], val[2])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 207)
  def _reduce_95(val, _values, result)
     result = SQLParser::Statement::Less.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 208)
  def _reduce_96(val, _values, result)
     result = SQLParser::Statement::Greater.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 209)
  def _reduce_97(val, _values, result)
     result = SQLParser::Statement::LessOrEquals.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 210)
  def _reduce_98(val, _values, result)
     result = SQLParser::Statement::GreaterOrEquals.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 99 omitted

# reduce 100 omitted

# reduce 101 omitted

# reduce 102 omitted

# reduce 103 omitted

module_eval(<<'.,.,', 'parser.racc', 224)
  def _reduce_104(val, _values, result)
     result = SQLParser::Statement::Add.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 225)
  def _reduce_105(val, _values, result)
     result = SQLParser::Statement::Subtract.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 106 omitted

module_eval(<<'.,.,', 'parser.racc', 229)
  def _reduce_107(val, _values, result)
     result = SQLParser::Statement::Multiply.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 230)
  def _reduce_108(val, _values, result)
     result = SQLParser::Statement::Divide.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 109 omitted

module_eval(<<'.,.,', 'parser.racc', 234)
  def _reduce_110(val, _values, result)
     result = val[0].new(val[1]) 
    result
  end
.,.,

# reduce 111 omitted

# reduce 112 omitted

# reduce 113 omitted

# reduce 114 omitted

module_eval(<<'.,.,', 'parser.racc', 241)
  def _reduce_115(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 116 omitted

# reduce 117 omitted

# reduce 118 omitted

# reduce 119 omitted

module_eval(<<'.,.,', 'parser.racc', 252)
  def _reduce_120(val, _values, result)
     result = SQLParser::Statement::CurrentUser.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 255)
  def _reduce_121(val, _values, result)
     result = SQLParser::Statement::QualifiedColumn.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 122 omitted

# reduce 123 omitted

module_eval(<<'.,.,', 'parser.racc', 262)
  def _reduce_124(val, _values, result)
     result = SQLParser::Statement::Count.new(SQLParser::Statement::All.new) 
    result
  end
.,.,

# reduce 125 omitted

module_eval(<<'.,.,', 'parser.racc', 266)
  def _reduce_126(val, _values, result)
     result = SQLParser::Statement::Count.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 267)
  def _reduce_127(val, _values, result)
     result = SQLParser::Statement::Average.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 268)
  def _reduce_128(val, _values, result)
     result = SQLParser::Statement::Maximum.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 269)
  def _reduce_129(val, _values, result)
     result = SQLParser::Statement::Minimum.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 270)
  def _reduce_130(val, _values, result)
     result = SQLParser::Statement::Sum.new(val[2]) 
    result
  end
.,.,

# reduce 131 omitted

# reduce 132 omitted

module_eval(<<'.,.,', 'parser.racc', 278)
  def _reduce_133(val, _values, result)
     result = SQLParser::Statement::Float.new("#{val[0]}.#{val[2]}".to_f) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 279)
  def _reduce_134(val, _values, result)
     result = SQLParser::Statement::Float.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 280)
  def _reduce_135(val, _values, result)
     result = SQLParser::Statement::Float.new("0.#{val[1]}".to_f) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 281)
  def _reduce_136(val, _values, result)
     result = SQLParser::Statement::Integer.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 284)
  def _reduce_137(val, _values, result)
     result = SQLParser::Statement::ApproximateFloat.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 138 omitted

# reduce 139 omitted

module_eval(<<'.,.,', 'parser.racc', 293)
  def _reduce_140(val, _values, result)
     result = val[0].new(SQLParser::Statement::Integer.new(val[1])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 294)
  def _reduce_141(val, _values, result)
     result = SQLParser::Statement::Integer.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 297)
  def _reduce_142(val, _values, result)
     result = SQLParser::Statement::UnaryPlus 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 298)
  def _reduce_143(val, _values, result)
     result = SQLParser::Statement::UnaryMinus 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 302)
  def _reduce_144(val, _values, result)
     result = SQLParser::Statement::Column.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 306)
  def _reduce_145(val, _values, result)
     result = SQLParser::Statement::String.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 307)
  def _reduce_146(val, _values, result)
     result = SQLParser::Statement::String.new('') 
    result
  end
.,.,

# reduce 147 omitted

# reduce 148 omitted

module_eval(<<'.,.,', 'parser.racc', 314)
  def _reduce_149(val, _values, result)
     result = SQLParser::Statement::Date.new(val[1]) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module SQLParser
