#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'

require File.dirname(__FILE__) + '/parser.rex.rb'

module SQLParser
  class Parser < Racc::Parser

module_eval(<<'...end parser.racc/module_eval...', 'parser.racc', 334)

def self.parse(sql)
  new.scan_str(sql)
end
...end parser.racc/module_eval...
##### State transition tables begin ###

racc_action_table = [
    44,  -126,    70,    28,    96,   231,    91,   220,    91,    85,
    84,   232,    18,    45,    44,    68,    69,   225,    67,    97,
    67,    99,   100,   203,   101,   102,    18,    45,     7,   127,
   222,     8,   223,   224,  -126,  -126,  -126,    71,   188,    65,
   206,    67,    47,    48,   207,    32,    36,    38,    39,    40,
    41,   103,    49,    67,    52,   214,    47,    48,    18,    32,
    36,    38,    39,    40,    41,   219,    49,    44,    52,   115,
   148,    47,    48,   131,   132,     8,   227,     8,   242,    18,
    45,   243,    96,    44,   188,   244,    28,   203,   227,   248,
   250,   188,    67,    18,   155,    18,    45,    97,   255,    99,
   100,   152,   101,   102,   211,   212,   257,   258,   259,    47,
    48,    67,    32,    36,    38,    39,    40,    41,     9,    49,
    11,    52,    12,    53,    54,    47,    48,    58,    32,    36,
    38,    39,    40,    41,    63,    49,    44,    52,    64,   148,
   -82,    75,    76,    77,    78,    79,    80,  -145,    18,    45,
    81,    82,    44,    83,    96,    28,    86,   105,    94,   107,
    58,    14,    95,   155,    18,    45,    67,   115,    67,    97,
   152,    99,   100,   123,   101,   102,   128,   129,    47,    48,
    95,    32,    36,    38,    39,    40,    41,   136,    49,   138,
    52,   139,   140,   141,    47,    48,   142,    32,    36,    38,
    39,    40,    41,   143,    49,    44,    52,    67,    28,   145,
   147,   168,   169,   170,   117,   171,   172,    18,    45,    44,
   173,   174,   225,   176,   177,   138,    58,   183,   184,   188,
   200,    18,    45,    44,   nil,   nil,    28,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    18,    45,    47,    48,   nil,
    32,    36,    38,    39,    40,    41,   nil,    49,   nil,    52,
   nil,    47,    48,   nil,    32,    36,    38,    39,    40,    41,
   nil,    49,   nil,    52,   nil,    47,    48,   nil,    32,    36,
    38,    39,    40,    41,   nil,    49,    44,    52,   nil,   225,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    18,    45,
    44,   nil,   nil,    28,   nil,   nil,   nil,   nil,     8,   nil,
   nil,   nil,    18,    45,    44,   nil,   nil,    28,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    18,    45,    47,    48,
   nil,    32,    36,    38,    39,    40,    41,   nil,    49,   nil,
    52,   nil,    47,    48,   nil,    32,    36,    38,    39,    40,
    41,   nil,    49,   nil,    52,   nil,    47,    48,   nil,    32,
    36,    38,    39,    40,    41,   nil,    49,    44,    52,   nil,
    28,   nil,   nil,   nil,   nil,     8,   nil,   nil,   nil,    18,
    45,    44,   nil,   nil,    28,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    18,    45,    44,   nil,   nil,    28,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    18,    45,    47,
    48,   nil,    32,    36,    38,    39,    40,    41,   nil,    49,
   nil,    52,   nil,    47,    48,   nil,    32,    36,    38,    39,
    40,    41,   nil,    49,   nil,    52,   nil,    47,    48,   nil,
    32,    36,    38,    39,    40,    41,   nil,    49,    44,    52,
   nil,   225,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    18,    45,   nil,   nil,   nil,    44,   nil,   nil,   148,   nil,
   189,   190,   nil,   191,   192,   193,   nil,    18,    45,   194,
   195,   196,   197,   198,   199,   nil,   nil,   nil,   nil,   nil,
    47,    48,   nil,    32,    36,    38,    39,    40,    41,   152,
    49,   nil,    52,   nil,   nil,   nil,   nil,    47,    48,   nil,
    32,    36,    38,    39,    40,    41,   nil,    49,    44,    52,
   nil,    28,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    44,
    18,    45,    28,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    18,    45,    44,   nil,   nil,    28,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    18,    45,   nil,   nil,   nil,
    47,    48,   nil,    32,    36,    38,    39,    40,    41,   nil,
    49,   nil,    52,   nil,    32,    36,    38,    39,    40,    41,
   nil,    49,   nil,    52,   nil,    47,    48,   nil,    32,    36,
    38,    39,    40,    41,   nil,    49,    44,    52,   nil,    28,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    18,    45,
   nil,   nil,   nil,    44,   nil,   nil,   148,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    18,    45,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    47,    48,
   155,    32,    36,    38,    39,    40,    41,   152,    49,   nil,
    52,   nil,   nil,   nil,   nil,    47,    48,   nil,    32,    36,
    38,    39,    40,    41,   nil,    49,    44,    52,   nil,    28,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    18,    45,
    44,   nil,   nil,    28,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    18,    45,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    47,    48,
   nil,    32,    36,    38,    39,    40,    41,   nil,    49,   nil,
    52,   nil,    47,    48,   nil,    32,    36,    38,    39,    40,
    41,   nil,    49,    44,    52,   nil,   148,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    18,    45,   nil,   nil,    44,
   nil,   nil,   225,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   155,    18,    45,   nil,   nil,   nil,   nil,   152,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    47,    48,   nil,    32,    36,
    38,    39,    40,    41,   nil,    49,   nil,    52,   nil,   nil,
   nil,    47,    48,   nil,    32,    36,    38,    39,    40,    41,
   nil,    49,    44,    52,   nil,    28,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    18,    45,    44,   nil,   nil,   225,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    18,    45,
    44,   nil,   nil,   225,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    18,    45,    47,    48,   nil,    32,    36,    38,
    39,    40,    41,   nil,    49,   nil,    52,   nil,    47,    48,
   nil,    32,    36,    38,    39,    40,    41,   nil,    49,   nil,
    52,   nil,    47,    48,   nil,    32,    36,    38,    39,    40,
    41,   nil,    49,    44,    52,   nil,   225,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    18,    45,    44,   nil,   nil,
   225,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    18,
    45,    44,   nil,   nil,   225,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    18,    45,    47,    48,   nil,    32,    36,
    38,    39,    40,    41,   nil,    49,   nil,    52,   nil,    47,
    48,   nil,    32,    36,    38,    39,    40,    41,   nil,    49,
   nil,    52,   nil,    47,    48,   nil,    32,    36,    38,    39,
    40,    41,   nil,    49,    44,    52,   nil,   225,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    18,    45,    44,   nil,
   nil,   225,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    18,    45,    44,   nil,   nil,    28,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    18,    45,    47,    48,   nil,    32,
    36,    38,    39,    40,    41,   nil,    49,   nil,    52,   nil,
    47,    48,   nil,    32,    36,    38,    39,    40,    41,   nil,
    49,   nil,    52,   nil,    47,    48,   nil,    32,    36,    38,
    39,    40,    41,   nil,    49,    44,    52,   nil,   148,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    18,    45,   nil,
   nil,    44,   nil,   nil,    28,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   155,    18,    45,   nil,   nil,   nil,   nil,   152,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    47,    48,   nil,
    32,    36,    38,    39,    40,    41,   nil,    49,   nil,    52,
   nil,   nil,   nil,    47,    48,   nil,    32,    36,    38,    39,
    40,    41,   nil,    49,    44,    52,   nil,   148,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    18,    45,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   155,   nil,   nil,   nil,   nil,   nil,   nil,   152,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    47,    48,   nil,    32,
    36,    38,    39,    40,    41,   nil,    49,   nil,    52 ]

racc_action_check = [
   136,    20,    22,   136,   108,   193,    54,   186,   129,    49,
    49,   193,   136,   136,   248,    21,    21,   248,    54,   108,
   129,   108,   108,   153,   108,   108,   248,   248,     0,    83,
   189,     0,   189,   189,    20,    20,    20,    22,   186,    17,
   178,    17,   136,   136,   179,   136,   136,   136,   136,   136,
   136,    56,   136,    56,   136,   182,   248,   248,   184,   248,
   248,   248,   248,   248,   248,   185,   248,   148,   248,   187,
   148,    83,    83,    89,    89,   148,   191,   200,   212,   148,
   148,   214,   181,    94,   215,   216,    94,   221,   223,   226,
   231,   241,   242,   244,   148,    94,    94,   181,   245,   181,
   181,   148,   181,   181,   181,   181,   249,   251,   252,   148,
   148,   259,   148,   148,   148,   148,   148,   148,     1,   148,
     5,   148,     7,     9,    11,    94,    94,    12,    94,    94,
    94,    94,    94,    94,    13,    94,   107,    94,    16,   107,
    18,    33,    36,    38,    39,    40,    41,    42,   107,   107,
    44,    45,     8,    46,    55,     8,    52,    58,    55,    62,
    63,     8,    55,   107,     8,     8,    65,    74,    75,    55,
   107,    55,    55,    81,    55,    55,    84,    87,   107,   107,
    93,   107,   107,   107,   107,   107,   107,    95,   107,    96,
   107,    97,    98,   100,     8,     8,   101,     8,     8,     8,
     8,     8,     8,   102,     8,    76,     8,   103,    76,   105,
   106,   117,   118,   119,    76,   120,   121,    76,    76,   222,
   122,   126,   222,   134,   135,   139,   140,   146,   147,   149,
   152,   222,   222,    77,   nil,   nil,    77,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    77,    77,    76,    76,   nil,
    76,    76,    76,    76,    76,    76,   nil,    76,   nil,    76,
   nil,   222,   222,   nil,   222,   222,   222,   222,   222,   222,
   nil,   222,   nil,   222,   nil,    77,    77,   nil,    77,    77,
    77,    77,    77,    77,   nil,    77,   224,    77,   nil,   224,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   224,   224,
   225,   nil,   nil,   225,   nil,   nil,   nil,   nil,   225,   nil,
   nil,   nil,   225,   225,    78,   nil,   nil,    78,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    78,    78,   224,   224,
   nil,   224,   224,   224,   224,   224,   224,   nil,   224,   nil,
   224,   nil,   225,   225,   nil,   225,   225,   225,   225,   225,
   225,   nil,   225,   nil,   225,   nil,    78,    78,   nil,    78,
    78,    78,    78,    78,    78,   nil,    78,   227,    78,   nil,
   227,   nil,   nil,   nil,   nil,   227,   nil,   nil,   nil,   227,
   227,    79,   nil,   nil,    79,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    79,    79,    80,   nil,   nil,    80,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    80,    80,   227,
   227,   nil,   227,   227,   227,   227,   227,   227,   nil,   227,
   nil,   227,   nil,    79,    79,   nil,    79,    79,    79,    79,
    79,    79,   nil,    79,   nil,    79,   nil,    80,    80,   nil,
    80,    80,    80,    80,    80,    80,   nil,    80,   255,    80,
   nil,   255,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   255,   255,   nil,   nil,   nil,   155,   nil,   nil,   155,   nil,
   151,   151,   nil,   151,   151,   151,   nil,   155,   155,   151,
   151,   151,   151,   151,   151,   nil,   nil,   nil,   nil,   nil,
   255,   255,   nil,   255,   255,   255,   255,   255,   255,   155,
   255,   nil,   255,   nil,   nil,   nil,   nil,   155,   155,   nil,
   155,   155,   155,   155,   155,   155,   nil,   155,   177,   155,
   nil,   177,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    23,
   177,   177,    23,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    23,    23,    28,   nil,   nil,    28,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    28,    28,   nil,   nil,   nil,
   177,   177,   nil,   177,   177,   177,   177,   177,   177,   nil,
   177,   nil,   177,   nil,    23,    23,    23,    23,    23,    23,
   nil,    23,   nil,    23,   nil,    28,    28,   nil,    28,    28,
    28,    28,    28,    28,   nil,    28,    64,    28,   nil,    64,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    64,    64,
   nil,   nil,   nil,   183,   nil,   nil,   183,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   183,   183,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    64,    64,
   183,    64,    64,    64,    64,    64,    64,   183,    64,   nil,
    64,   nil,   nil,   nil,   nil,   183,   183,   nil,   183,   183,
   183,   183,   183,   183,   nil,   183,    68,   183,   nil,    68,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    68,    68,
    69,   nil,   nil,    69,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    69,    69,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    68,    68,
   nil,    68,    68,    68,    68,    68,    68,   nil,    68,   nil,
    68,   nil,    69,    69,   nil,    69,    69,    69,    69,    69,
    69,   nil,    69,   188,    69,   nil,   188,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   188,   188,   nil,   nil,   190,
   nil,   nil,   190,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   188,   190,   190,   nil,   nil,   nil,   nil,   188,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   188,   188,   nil,   188,   188,
   188,   188,   188,   188,   nil,   188,   nil,   188,   nil,   nil,
   nil,   190,   190,   nil,   190,   190,   190,   190,   190,   190,
   nil,   190,    70,   190,   nil,    70,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    70,    70,   192,   nil,   nil,   192,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   192,   192,
   194,   nil,   nil,   194,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   194,   194,    70,    70,   nil,    70,    70,    70,
    70,    70,    70,   nil,    70,   nil,    70,   nil,   192,   192,
   nil,   192,   192,   192,   192,   192,   192,   nil,   192,   nil,
   192,   nil,   194,   194,   nil,   194,   194,   194,   194,   194,
   194,   nil,   194,   195,   194,   nil,   195,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   195,   195,   196,   nil,   nil,
   196,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   196,
   196,   197,   nil,   nil,   197,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   197,   197,   195,   195,   nil,   195,   195,
   195,   195,   195,   195,   nil,   195,   nil,   195,   nil,   196,
   196,   nil,   196,   196,   196,   196,   196,   196,   nil,   196,
   nil,   196,   nil,   197,   197,   nil,   197,   197,   197,   197,
   197,   197,   nil,   197,   198,   197,   nil,   198,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   198,   198,   199,   nil,
   nil,   199,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   199,   199,    71,   nil,   nil,    71,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    71,    71,   198,   198,   nil,   198,
   198,   198,   198,   198,   198,   nil,   198,   nil,   198,   nil,
   199,   199,   nil,   199,   199,   199,   199,   199,   199,   nil,
   199,   nil,   199,   nil,    71,    71,   nil,    71,    71,    71,
    71,    71,    71,   nil,    71,   203,    71,   nil,   203,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   203,   203,   nil,
   nil,   207,   nil,   nil,   207,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   203,   207,   207,   nil,   nil,   nil,   nil,   203,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   203,   203,   nil,
   203,   203,   203,   203,   203,   203,   nil,   203,   nil,   203,
   nil,   nil,   nil,   207,   207,   nil,   207,   207,   207,   207,
   207,   207,   nil,   207,   211,   207,   nil,   211,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   211,   211,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   211,   nil,   nil,   nil,   nil,   nil,   nil,   211,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   211,   211,   nil,   211,
   211,   211,   211,   211,   211,   nil,   211,   nil,   211 ]

racc_action_pointer = [
    18,   118,   nil,   nil,   nil,   118,   nil,   111,   147,   123,
   nil,   121,   110,   118,   nil,   nil,   134,    24,   122,   nil,
   -13,   -32,   -12,   524,   nil,   nil,   nil,   nil,   538,   nil,
   nil,   nil,   nil,   123,   nil,   nil,   134,   nil,   135,   136,
   137,   138,    91,   nil,   132,   146,    97,   nil,   nil,   -48,
   nil,   nil,    96,   nil,     1,   150,    36,   nil,   139,   nil,
   nil,   nil,   131,   143,   591,   149,   nil,   nil,   661,   675,
   797,   987,   nil,   nil,   158,   151,   200,   228,   309,   376,
   390,   168,   nil,    24,   119,   nil,   nil,   173,   nil,    67,
   nil,   nil,   nil,   168,    78,   179,   172,   171,   172,   nil,
   170,   173,   180,   190,   nil,   192,   181,   131,     0,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   202,   203,   204,
   206,   207,   211,   nil,   nil,   nil,   216,   nil,   nil,     3,
   nil,   nil,   nil,   nil,   214,   220,    -5,   nil,   nil,   208,
   209,   nil,   nil,   nil,   nil,   nil,   197,   225,    62,   189,
   nil,   438,   222,   -11,   nil,   460,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   513,    31,    40,
   nil,    78,    24,   608,    41,    56,    -2,    60,   728,    -3,
   744,    68,   811,   -27,   825,   878,   892,   906,   959,   973,
    64,   nil,   nil,  1040,   nil,   nil,   nil,  1056,   nil,   nil,
   nil,  1109,    70,   nil,    76,    44,    81,   nil,   nil,   nil,
   nil,    53,   214,    80,   281,   295,    55,   362,   nil,   nil,
   nil,    52,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    51,    75,   nil,    76,    64,   nil,   nil,     9,    97,
   nil,    98,   104,   nil,   nil,   443,   nil,   nil,   nil,    94,
   nil,   nil ]

racc_action_default = [
  -157,  -157,    -1,    -2,    -3,    -5,   -16,  -157,  -157,  -157,
    -4,  -157,  -157,   -24,   -25,   -26,   -28,   -31,  -151,  -109,
  -110,  -113,  -116,  -157,  -118,  -119,  -120,  -121,  -157,  -123,
  -124,  -125,  -127,  -157,  -129,  -130,  -157,  -132,  -157,  -157,
  -157,  -157,  -138,  -139,  -143,  -157,  -157,  -149,  -150,  -157,
  -154,  -155,  -157,   262,  -157,  -157,   -36,   -37,   -82,   -40,
   -41,   -23,   -57,  -157,  -157,  -157,   -30,  -151,  -157,  -157,
  -157,  -157,  -117,  -126,  -157,  -157,  -157,  -157,  -157,  -157,
  -157,  -141,  -142,  -157,  -157,  -153,  -156,    -6,    -8,   -12,
   -10,   -11,   -17,  -157,  -157,  -157,  -157,  -157,  -157,   -45,
   -47,   -49,   -50,  -157,   -35,  -157,   -59,  -157,   -33,   -27,
   -29,  -111,  -112,  -114,  -115,  -122,  -128,  -157,  -157,  -157,
  -157,  -157,  -157,  -140,  -144,  -146,  -157,  -148,  -152,  -157,
    -9,   -13,   -14,   -18,  -157,   -21,  -157,   -42,   -82,  -157,
  -157,   -46,   -48,   -51,   -34,   -38,   -64,  -157,  -157,   -58,
   -68,  -157,  -157,   -85,   -87,  -157,   -90,   -91,   -92,   -94,
   -95,   -96,   -97,   -98,   -99,  -106,  -107,  -108,  -131,  -133,
  -134,  -135,  -136,  -137,  -147,    -7,   -19,  -157,  -157,   -76,
   -43,  -157,   -66,  -157,  -157,  -157,  -157,  -108,  -157,  -157,
  -157,  -157,  -157,  -157,  -157,  -157,  -157,  -157,  -157,  -157,
  -157,   -39,   -81,  -157,   -89,   -20,   -22,  -157,   -44,   -52,
   -53,  -157,  -157,   -32,  -157,   -65,   -60,   -62,   -63,   -15,
   -93,   -86,  -157,  -157,  -157,  -157,  -157,  -157,   -72,   -73,
   -78,  -157,   -80,  -100,  -101,  -102,  -103,  -104,  -105,   -88,
   -75,   -54,  -157,   -67,  -157,  -157,   -71,   -77,  -157,  -157,
   -79,  -157,   -56,   -84,   -61,  -157,   -70,   -74,   -55,  -157,
   -69,   -83 ]

racc_goto_table = [
    66,    17,    55,   149,    56,   178,   134,    88,   218,   226,
   201,   230,    92,   233,   234,   235,   236,   237,   238,    15,
   217,    74,   228,   113,   114,   111,   112,   209,   210,   251,
   252,   216,   221,   239,   204,   126,    72,    90,   124,   104,
   125,   245,   213,   247,   186,    73,     2,     3,   110,   201,
   133,     4,     5,   108,   246,    56,    10,    17,   116,    87,
   130,    93,    13,    61,    62,   106,   146,   256,   218,   118,
   119,   120,   121,   122,   260,   109,   240,   182,     1,   215,
   254,   201,   175,   202,   208,   nil,   144,   135,   137,   205,
    73,    73,    73,    73,   nil,   nil,   249,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   241,   nil,   nil,
   nil,   nil,    90,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   179,
   181,   180,    56,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   187,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   135,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   179,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    74,   nil,
   179,   nil,   nil,   nil,   nil,   253,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   261 ]

racc_goto_check = [
    11,    18,    14,    38,    29,    19,    17,     8,    43,    46,
    12,    46,    15,    46,    46,    46,    46,    46,    46,    22,
    42,    18,    48,    61,    61,    59,    59,    36,    37,    39,
    40,    41,    52,    53,    54,    63,    64,    11,    75,    11,
    76,    46,    28,    46,    38,    60,     2,     3,    11,    12,
    15,     4,     5,    14,    48,    29,     6,    18,    11,     7,
    10,    16,    20,    21,    24,    25,    26,    46,    43,    18,
    18,    18,    18,    18,    46,    22,    19,    27,     1,    38,
    42,    12,     8,    31,    35,   nil,    11,    18,    29,    17,
    60,    60,    60,    60,   nil,   nil,    19,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    38,   nil,   nil,
   nil,   nil,    11,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    18,
    14,    29,    29,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    18,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    18,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    18,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    18,   nil,
    18,   nil,   nil,   nil,   nil,    11,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    11 ]

racc_goto_pointer = [
   nil,    78,    46,    47,    51,    52,    51,     5,   -47,   nil,
   -29,   -17,  -142,   nil,   -10,   -43,     6,   -88,    -7,  -131,
    54,    50,    11,   nil,    51,     3,   -40,   -69,  -140,    -8,
   nil,   -69,   nil,   nil,   nil,   -97,  -154,  -153,  -104,  -213,
  -212,  -153,  -164,  -176,   nil,   nil,  -181,   nil,  -169,   nil,
   nil,   nil,  -156,  -170,  -121,   nil,   nil,   nil,   nil,   -43,
    22,   -47,   nil,   -48,    13,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   -45,   -43,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   185,   nil,   nil,   nil,    89,
   nil,    34,   150,     6,   nil,   nil,   nil,   nil,   167,   nil,
   nil,   nil,   nil,    16,   nil,   nil,   nil,   nil,   nil,    35,
    57,   229,    59,    60,    98,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    26,   166,   160,   151,   161,   nil,   162,
   163,   164,   153,   154,   156,   157,   158,   159,   165,    19,
    20,    21,    22,    23,    24,    25,    27,    29,    30,    31,
    33,    37,    42,    43,    46,   nil,   nil,    50,    51 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 62, :_reduce_none,
  1, 63, :_reduce_none,
  1, 63, :_reduce_none,
  2, 64, :_reduce_4,
  0, 67, :_reduce_none,
  3, 67, :_reduce_6,
  3, 68, :_reduce_7,
  1, 68, :_reduce_none,
  2, 69, :_reduce_9,
  1, 70, :_reduce_none,
  1, 70, :_reduce_11,
  0, 71, :_reduce_12,
  1, 71, :_reduce_13,
  1, 71, :_reduce_14,
  3, 73, :_reduce_15,
  1, 66, :_reduce_none,
  4, 65, :_reduce_17,
  5, 65, :_reduce_18,
  3, 77, :_reduce_19,
  3, 78, :_reduce_20,
  1, 78, :_reduce_none,
  4, 76, :_reduce_22,
  3, 74, :_reduce_23,
  2, 74, :_reduce_24,
  1, 81, :_reduce_25,
  1, 81, :_reduce_26,
  3, 83, :_reduce_27,
  1, 83, :_reduce_none,
  3, 84, :_reduce_29,
  2, 84, :_reduce_30,
  1, 84, :_reduce_none,
  5, 82, :_reduce_32,
  2, 85, :_reduce_33,
  3, 75, :_reduce_34,
  2, 75, :_reduce_35,
  1, 75, :_reduce_none,
  1, 75, :_reduce_none,
  3, 75, :_reduce_38,
  1, 92, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  3, 93, :_reduce_42,
  4, 93, :_reduce_43,
  5, 94, :_reduce_44,
  1, 95, :_reduce_45,
  2, 95, :_reduce_46,
  1, 95, :_reduce_47,
  2, 95, :_reduce_48,
  1, 95, :_reduce_49,
  1, 95, :_reduce_50,
  2, 95, :_reduce_51,
  1, 96, :_reduce_none,
  1, 96, :_reduce_none,
  2, 97, :_reduce_54,
  4, 98, :_reduce_55,
  1, 100, :_reduce_none,
  0, 86, :_reduce_none,
  2, 86, :_reduce_58,
  0, 87, :_reduce_none,
  3, 87, :_reduce_60,
  3, 102, :_reduce_61,
  1, 102, :_reduce_none,
  1, 103, :_reduce_none,
  0, 88, :_reduce_none,
  2, 88, :_reduce_65,
  0, 89, :_reduce_none,
  2, 89, :_reduce_67,
  1, 105, :_reduce_none,
  6, 106, :_reduce_69,
  5, 106, :_reduce_70,
  4, 108, :_reduce_71,
  3, 108, :_reduce_72,
  1, 109, :_reduce_none,
  3, 109, :_reduce_74,
  3, 80, :_reduce_75,
  1, 80, :_reduce_none,
  4, 110, :_reduce_77,
  3, 110, :_reduce_78,
  4, 111, :_reduce_79,
  3, 111, :_reduce_80,
  2, 112, :_reduce_81,
  1, 90, :_reduce_82,
  3, 101, :_reduce_83,
  1, 101, :_reduce_none,
  1, 99, :_reduce_none,
  3, 99, :_reduce_86,
  1, 113, :_reduce_none,
  3, 113, :_reduce_88,
  2, 114, :_reduce_89,
  1, 114, :_reduce_none,
  1, 115, :_reduce_none,
  1, 116, :_reduce_none,
  3, 116, :_reduce_93,
  1, 117, :_reduce_none,
  1, 117, :_reduce_none,
  1, 117, :_reduce_none,
  1, 117, :_reduce_none,
  1, 117, :_reduce_none,
  1, 117, :_reduce_none,
  3, 118, :_reduce_100,
  3, 118, :_reduce_101,
  3, 118, :_reduce_102,
  3, 118, :_reduce_103,
  3, 118, :_reduce_104,
  3, 118, :_reduce_105,
  1, 107, :_reduce_none,
  1, 107, :_reduce_none,
  1, 119, :_reduce_none,
  1, 79, :_reduce_none,
  1, 79, :_reduce_none,
  3, 120, :_reduce_111,
  3, 120, :_reduce_112,
  1, 120, :_reduce_none,
  3, 122, :_reduce_114,
  3, 122, :_reduce_115,
  1, 122, :_reduce_none,
  2, 123, :_reduce_117,
  1, 123, :_reduce_none,
  1, 125, :_reduce_none,
  1, 125, :_reduce_none,
  1, 125, :_reduce_none,
  3, 125, :_reduce_122,
  1, 126, :_reduce_none,
  1, 126, :_reduce_none,
  1, 128, :_reduce_none,
  1, 128, :_reduce_none,
  1, 129, :_reduce_127,
  3, 104, :_reduce_128,
  1, 104, :_reduce_none,
  1, 131, :_reduce_none,
  4, 127, :_reduce_131,
  1, 127, :_reduce_none,
  4, 132, :_reduce_133,
  4, 132, :_reduce_134,
  4, 132, :_reduce_135,
  4, 132, :_reduce_136,
  4, 132, :_reduce_137,
  1, 130, :_reduce_none,
  1, 130, :_reduce_none,
  3, 133, :_reduce_140,
  2, 133, :_reduce_141,
  2, 133, :_reduce_142,
  1, 133, :_reduce_143,
  3, 134, :_reduce_144,
  1, 135, :_reduce_none,
  1, 136, :_reduce_none,
  2, 137, :_reduce_147,
  1, 137, :_reduce_148,
  1, 124, :_reduce_149,
  1, 124, :_reduce_150,
  1, 72, :_reduce_151,
  3, 121, :_reduce_152,
  2, 121, :_reduce_153,
  1, 121, :_reduce_none,
  1, 138, :_reduce_none,
  2, 139, :_reduce_156 ]

racc_reduce_n = 157

racc_shift_n = 262

racc_token_table = {
  false => 0,
  :error => 1,
  :ORDER => 2,
  :BY => 3,
  :comma => 4,
  :unsigned_integer => 5,
  :ASC => 6,
  :DESC => 7,
  :left_paren => 8,
  :right_paren => 9,
  :INSERT => 10,
  :INTO => 11,
  :VALUES => 12,
  :SELECT => 13,
  :asterisk => 14,
  :AS => 15,
  :FROM => 16,
  :identifier => 17,
  :period => 18,
  :CROSS => 19,
  :JOIN => 20,
  :INNER => 21,
  :LEFT => 22,
  :OUTER => 23,
  :RIGHT => 24,
  :FULL => 25,
  :ON => 26,
  :USING => 27,
  :WHERE => 28,
  :GROUP => 29,
  :HAVING => 30,
  :LIMIT => 31,
  :NOT => 32,
  :BETWEEN => 33,
  :AND => 34,
  :IN => 35,
  :LIKE => 36,
  :IS => 37,
  :NULL => 38,
  :EXISTS => 39,
  :OR => 40,
  :equals_operator => 41,
  :not_equals_operator => 42,
  :less_than_operator => 43,
  :greater_than_operator => 44,
  :less_than_or_equals_operator => 45,
  :greater_than_or_equals_operator => 46,
  :plus_sign => 47,
  :minus_sign => 48,
  :solidus => 49,
  :CURRENT_USER => 50,
  :COUNT => 51,
  :AVG => 52,
  :MAX => 53,
  :MIN => 54,
  :SUM => 55,
  :E => 56,
  :quote => 57,
  :character_string_literal => 58,
  :DATE => 59,
  :date_string => 60 }

racc_nt_base = 61

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "ORDER",
  "BY",
  "comma",
  "unsigned_integer",
  "ASC",
  "DESC",
  "left_paren",
  "right_paren",
  "INSERT",
  "INTO",
  "VALUES",
  "SELECT",
  "asterisk",
  "AS",
  "FROM",
  "identifier",
  "period",
  "CROSS",
  "JOIN",
  "INNER",
  "LEFT",
  "OUTER",
  "RIGHT",
  "FULL",
  "ON",
  "USING",
  "WHERE",
  "GROUP",
  "HAVING",
  "LIMIT",
  "NOT",
  "BETWEEN",
  "AND",
  "IN",
  "LIKE",
  "IS",
  "NULL",
  "EXISTS",
  "OR",
  "equals_operator",
  "not_equals_operator",
  "less_than_operator",
  "greater_than_operator",
  "less_than_or_equals_operator",
  "greater_than_or_equals_operator",
  "plus_sign",
  "minus_sign",
  "solidus",
  "CURRENT_USER",
  "COUNT",
  "AVG",
  "MAX",
  "MIN",
  "SUM",
  "E",
  "quote",
  "character_string_literal",
  "DATE",
  "date_string",
  "$start",
  "direct_sql_statement",
  "direct_sql_data_statement",
  "direct_select_statement_multiple_rows",
  "insert_specification",
  "query_expression",
  "order_by_clause",
  "sort_specification_list",
  "sort_specification",
  "sort_key",
  "ordering_specification",
  "column_name",
  "subquery",
  "query_specification",
  "table_reference",
  "value_list",
  "column_list",
  "in_column_list",
  "value_expression",
  "in_value_list",
  "select_list",
  "table_expression",
  "select_sublist",
  "derived_column",
  "from_clause",
  "where_clause",
  "group_by_clause",
  "having_clause",
  "limit_clause",
  "table_name",
  "joined_table",
  "table_subquery",
  "cross_join",
  "qualified_join",
  "join_type",
  "join_specification",
  "join_condition",
  "named_columns_join",
  "search_condition",
  "join_column_list",
  "column_name_list",
  "grouping_column_reference_list",
  "grouping_column_reference",
  "column_reference",
  "row_subquery",
  "between_predicate",
  "row_value_constructor",
  "in_predicate",
  "in_predicate_value",
  "like_predicate",
  "null_predicate",
  "exists_predicate",
  "boolean_term",
  "boolean_factor",
  "boolean_test",
  "boolean_primary",
  "predicate",
  "comparison_predicate",
  "row_value_constructor_element",
  "numeric_value_expression",
  "general_literal",
  "term",
  "factor",
  "sign",
  "value_expression_primary",
  "unsigned_value_specification",
  "set_function_specification",
  "unsigned_literal",
  "general_value_specification",
  "unsigned_numeric_literal",
  "qualifier",
  "general_set_function",
  "exact_numeric_literal",
  "approximate_numeric_literal",
  "mantissa",
  "exponent",
  "signed_integer",
  "datetime_literal",
  "date_literal" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

module_eval(<<'.,.,', 'parser.racc', 13)
  def _reduce_4(val, _values, result)
     result = SQLParser::Statement::DirectSelect.new(val[0], val[1]) 
    result
  end
.,.,

# reduce 5 omitted

module_eval(<<'.,.,', 'parser.racc', 18)
  def _reduce_6(val, _values, result)
     result = SQLParser::Statement::OrderBy.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 21)
  def _reduce_7(val, _values, result)
     result = Array(val[0]) + Array(val[2]) 
    result
  end
.,.,

# reduce 8 omitted

module_eval(<<'.,.,', 'parser.racc', 25)
  def _reduce_9(val, _values, result)
     result = val[1].new(val[0]) 
    result
  end
.,.,

# reduce 10 omitted

module_eval(<<'.,.,', 'parser.racc', 29)
  def _reduce_11(val, _values, result)
     result = SQLParser::Statement::Integer.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 32)
  def _reduce_12(val, _values, result)
     result = SQLParser::Statement::Ascending 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 33)
  def _reduce_13(val, _values, result)
     result = SQLParser::Statement::Ascending 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 34)
  def _reduce_14(val, _values, result)
     result = SQLParser::Statement::Descending 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 39)
  def _reduce_15(val, _values, result)
     result = SQLParser::Statement::Subquery.new(val[1]) 
    result
  end
.,.,

# reduce 16 omitted

module_eval(<<'.,.,', 'parser.racc', 45)
  def _reduce_17(val, _values, result)
     result = SQLParser::Statement::Insert.new(val[2], nil, val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 46)
  def _reduce_18(val, _values, result)
     result = SQLParser::Statement::Insert.new(val[2], val[3], val[4]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 49)
  def _reduce_19(val, _values, result)
     result = SQLParser::Statement::InColumnList.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 52)
  def _reduce_20(val, _values, result)
     result = Array(val[0]) + Array(val[2]) 
    result
  end
.,.,

# reduce 21 omitted

module_eval(<<'.,.,', 'parser.racc', 56)
  def _reduce_22(val, _values, result)
     result = SQLParser::Statement::InValueList.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 59)
  def _reduce_23(val, _values, result)
     result = SQLParser::Statement::Select.new(val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 60)
  def _reduce_24(val, _values, result)
     result = SQLParser::Statement::Select.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 63)
  def _reduce_25(val, _values, result)
     result = SQLParser::Statement::All.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 64)
  def _reduce_26(val, _values, result)
     result = SQLParser::Statement::SelectList.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 67)
  def _reduce_27(val, _values, result)
     result = Array(val[0]) + Array(val[2]) 
    result
  end
.,.,

# reduce 28 omitted

module_eval(<<'.,.,', 'parser.racc', 71)
  def _reduce_29(val, _values, result)
     result = SQLParser::Statement::As.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 72)
  def _reduce_30(val, _values, result)
     result = SQLParser::Statement::As.new(val[0], val[1]) 
    result
  end
.,.,

# reduce 31 omitted

module_eval(<<'.,.,', 'parser.racc', 76)
  def _reduce_32(val, _values, result)
     result = SQLParser::Statement::TableExpression.new(val[0], val[1], val[2], val[3], val[4]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 79)
  def _reduce_33(val, _values, result)
     result = SQLParser::Statement::FromClause.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 82)
  def _reduce_34(val, _values, result)
     result = SQLParser::Statement::As.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 83)
  def _reduce_35(val, _values, result)
     result = SQLParser::Statement::As.new(val[0], val[1]) 
    result
  end
.,.,

# reduce 36 omitted

# reduce 37 omitted

module_eval(<<'.,.,', 'parser.racc', 86)
  def _reduce_38(val, _values, result)
     result = SQLParser::Statement::Table.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

module_eval(<<'.,.,', 'parser.racc', 96)
  def _reduce_42(val, _values, result)
     result = SQLParser::Statement::CrossJoin.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 97)
  def _reduce_43(val, _values, result)
     result = SQLParser::Statement::CrossJoin.new(val[0], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 100)
  def _reduce_44(val, _values, result)
     result = val[1].new(val[0], val[3], val[4]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 103)
  def _reduce_45(val, _values, result)
     result = SQLParser::Statement::InnerJoin 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 104)
  def _reduce_46(val, _values, result)
     result = SQLParser::Statement::LeftOuterJoin 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 105)
  def _reduce_47(val, _values, result)
     result = SQLParser::Statement::LeftJoin 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 106)
  def _reduce_48(val, _values, result)
     result = SQLParser::Statement::RightOuterJoin 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 107)
  def _reduce_49(val, _values, result)
     result = SQLParser::Statement::RightJoin 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 108)
  def _reduce_50(val, _values, result)
     result = SQLParser::Statement::FullJoin 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 109)
  def _reduce_51(val, _values, result)
     result = SQLParser::Statement::FullOuterJoin 
    result
  end
.,.,

# reduce 52 omitted

# reduce 53 omitted

module_eval(<<'.,.,', 'parser.racc', 116)
  def _reduce_54(val, _values, result)
     result = SQLParser::Statement::On.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 119)
  def _reduce_55(val, _values, result)
     result = SQLParser::Statement::Using.new(val[2]) 
    result
  end
.,.,

# reduce 56 omitted

# reduce 57 omitted

module_eval(<<'.,.,', 'parser.racc', 126)
  def _reduce_58(val, _values, result)
     result = SQLParser::Statement::WhereClause.new(val[1]) 
    result
  end
.,.,

# reduce 59 omitted

module_eval(<<'.,.,', 'parser.racc', 130)
  def _reduce_60(val, _values, result)
     result = SQLParser::Statement::GroupByClause.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 133)
  def _reduce_61(val, _values, result)
     result = Array(val[0]) + Array(val[2]) 
    result
  end
.,.,

# reduce 62 omitted

# reduce 63 omitted

# reduce 64 omitted

module_eval(<<'.,.,', 'parser.racc', 141)
  def _reduce_65(val, _values, result)
     result = SQLParser::Statement::HavingClause.new(val[1]) 
    result
  end
.,.,

# reduce 66 omitted

module_eval(<<'.,.,', 'parser.racc', 145)
  def _reduce_67(val, _values, result)
     result = SQLParser::Statement::LimitClause.new(SQLParser::Statement::Integer.new(val[1])) 
    result
  end
.,.,

# reduce 68 omitted

module_eval(<<'.,.,', 'parser.racc', 152)
  def _reduce_69(val, _values, result)
     result = SQLParser::Statement::Not.new(SQLParser::Statement::Between.new(val[0], val[3], val[5])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 153)
  def _reduce_70(val, _values, result)
     result = SQLParser::Statement::Between.new(val[0], val[2], val[4]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 156)
  def _reduce_71(val, _values, result)
     result = SQLParser::Statement::Not.new(SQLParser::Statement::In.new(val[0], val[3])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 157)
  def _reduce_72(val, _values, result)
     result = SQLParser::Statement::In.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 73 omitted

module_eval(<<'.,.,', 'parser.racc', 161)
  def _reduce_74(val, _values, result)
     result = SQLParser::Statement::InValueList.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 164)
  def _reduce_75(val, _values, result)
     result = Array(val[0]) + Array(val[2]) 
    result
  end
.,.,

# reduce 76 omitted

module_eval(<<'.,.,', 'parser.racc', 171)
  def _reduce_77(val, _values, result)
     result = SQLParser::Statement::Not.new(SQLParser::Statement::Like.new(val[0], val[3])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 172)
  def _reduce_78(val, _values, result)
     result = SQLParser::Statement::Like.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 175)
  def _reduce_79(val, _values, result)
     result = SQLParser::Statement::Not.new(SQLParser::Statement::Is.new(val[0], SQLParser::Statement::Null.new)) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 176)
  def _reduce_80(val, _values, result)
     result = SQLParser::Statement::Is.new(val[0], SQLParser::Statement::Null.new) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 179)
  def _reduce_81(val, _values, result)
     result = SQLParser::Statement::Exists.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 183)
  def _reduce_82(val, _values, result)
     result = SQLParser::Statement::Table.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 186)
  def _reduce_83(val, _values, result)
     result = Array(val[0]) + Array(val[2]) 
    result
  end
.,.,

# reduce 84 omitted

# reduce 85 omitted

module_eval(<<'.,.,', 'parser.racc', 192)
  def _reduce_86(val, _values, result)
     result = SQLParser::Statement::Or.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 87 omitted

module_eval(<<'.,.,', 'parser.racc', 196)
  def _reduce_88(val, _values, result)
     result = SQLParser::Statement::And.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 199)
  def _reduce_89(val, _values, result)
     result = SQLParser::Statement::Not.new(val[1]) 
    result
  end
.,.,

# reduce 90 omitted

# reduce 91 omitted

# reduce 92 omitted

module_eval(<<'.,.,', 'parser.racc', 207)
  def _reduce_93(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 94 omitted

# reduce 95 omitted

# reduce 96 omitted

# reduce 97 omitted

# reduce 98 omitted

# reduce 99 omitted

module_eval(<<'.,.,', 'parser.racc', 218)
  def _reduce_100(val, _values, result)
     result = SQLParser::Statement::Equals.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 219)
  def _reduce_101(val, _values, result)
     result = SQLParser::Statement::Not.new(SQLParser::Statement::Equals.new(val[0], val[2])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 220)
  def _reduce_102(val, _values, result)
     result = SQLParser::Statement::Less.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 221)
  def _reduce_103(val, _values, result)
     result = SQLParser::Statement::Greater.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 222)
  def _reduce_104(val, _values, result)
     result = SQLParser::Statement::LessOrEquals.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 223)
  def _reduce_105(val, _values, result)
     result = SQLParser::Statement::GreaterOrEquals.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 106 omitted

# reduce 107 omitted

# reduce 108 omitted

# reduce 109 omitted

# reduce 110 omitted

module_eval(<<'.,.,', 'parser.racc', 237)
  def _reduce_111(val, _values, result)
     result = SQLParser::Statement::Add.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 238)
  def _reduce_112(val, _values, result)
     result = SQLParser::Statement::Subtract.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 113 omitted

module_eval(<<'.,.,', 'parser.racc', 242)
  def _reduce_114(val, _values, result)
     result = SQLParser::Statement::Multiply.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 243)
  def _reduce_115(val, _values, result)
     result = SQLParser::Statement::Divide.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 116 omitted

module_eval(<<'.,.,', 'parser.racc', 247)
  def _reduce_117(val, _values, result)
     result = val[0].new(val[1]) 
    result
  end
.,.,

# reduce 118 omitted

# reduce 119 omitted

# reduce 120 omitted

# reduce 121 omitted

module_eval(<<'.,.,', 'parser.racc', 254)
  def _reduce_122(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 123 omitted

# reduce 124 omitted

# reduce 125 omitted

# reduce 126 omitted

module_eval(<<'.,.,', 'parser.racc', 265)
  def _reduce_127(val, _values, result)
     result = SQLParser::Statement::CurrentUser.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 268)
  def _reduce_128(val, _values, result)
     result = SQLParser::Statement::QualifiedColumn.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 129 omitted

# reduce 130 omitted

module_eval(<<'.,.,', 'parser.racc', 275)
  def _reduce_131(val, _values, result)
     result = SQLParser::Statement::Count.new(SQLParser::Statement::All.new) 
    result
  end
.,.,

# reduce 132 omitted

module_eval(<<'.,.,', 'parser.racc', 279)
  def _reduce_133(val, _values, result)
     result = SQLParser::Statement::Count.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 280)
  def _reduce_134(val, _values, result)
     result = SQLParser::Statement::Average.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 281)
  def _reduce_135(val, _values, result)
     result = SQLParser::Statement::Maximum.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 282)
  def _reduce_136(val, _values, result)
     result = SQLParser::Statement::Minimum.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 283)
  def _reduce_137(val, _values, result)
     result = SQLParser::Statement::Sum.new(val[2]) 
    result
  end
.,.,

# reduce 138 omitted

# reduce 139 omitted

module_eval(<<'.,.,', 'parser.racc', 291)
  def _reduce_140(val, _values, result)
     result = SQLParser::Statement::Float.new("#{val[0]}.#{val[2]}".to_f) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 292)
  def _reduce_141(val, _values, result)
     result = SQLParser::Statement::Float.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 293)
  def _reduce_142(val, _values, result)
     result = SQLParser::Statement::Float.new("0.#{val[1]}".to_f) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 294)
  def _reduce_143(val, _values, result)
     result = SQLParser::Statement::Integer.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 297)
  def _reduce_144(val, _values, result)
     result = SQLParser::Statement::ApproximateFloat.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 145 omitted

# reduce 146 omitted

module_eval(<<'.,.,', 'parser.racc', 306)
  def _reduce_147(val, _values, result)
     result = val[0].new(SQLParser::Statement::Integer.new(val[1])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 307)
  def _reduce_148(val, _values, result)
     result = SQLParser::Statement::Integer.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 310)
  def _reduce_149(val, _values, result)
     result = SQLParser::Statement::UnaryPlus 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 311)
  def _reduce_150(val, _values, result)
     result = SQLParser::Statement::UnaryMinus 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 315)
  def _reduce_151(val, _values, result)
     result = SQLParser::Statement::Column.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 319)
  def _reduce_152(val, _values, result)
     result = SQLParser::Statement::String.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 320)
  def _reduce_153(val, _values, result)
     result = SQLParser::Statement::String.new('') 
    result
  end
.,.,

# reduce 154 omitted

# reduce 155 omitted

module_eval(<<'.,.,', 'parser.racc', 327)
  def _reduce_156(val, _values, result)
     result = SQLParser::Statement::Date.new(val[1]) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module SQLParser
